services:
  db:
    image: pgvector/pgvector:0.7.4-pg15
    volumes:
      - helperai_pgdata:/var/lib/postgresql/data
    ports:
      - 5435:5432
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: helperai_development

  redis:
    image: redis:7.0.12
    command: [ "redis-server", "--appendonly", "yes" ]
    ports:
      - 6382:6379
    volumes:
      - ./tmp/redis:/data

  serverless-redis-http:
    ports:
      - "8089:80"
    image: hiett/serverless-redis-http:latest
    environment:
      SRH_MODE: env
      SRH_TOKEN: example_token
      SRH_CONNECTION_STRING: "redis://redis:6379"
    depends_on:
      - redis

  nginx:
    image: nginx:1.27.2
    volumes:
      - ./local-nginx/helperai_dev.conf:/etc/nginx/conf.d/default.conf
      - ./local-nginx/certs:/etc/ssl/certs/
    ports:
      - 80:80
      - 443:443
    extra_hosts:
      - "host.docker.internal:host-gateway"

  # langfuse-server:
  #   image: langfuse/langfuse:2
  #   ports:
  #     - "3020:3000"
  #   environment:
  #     - DATABASE_URL=postgresql://username:password@db:5432/langfuse
  #     - NEXTAUTH_SECRET=mysecret
  #     - SALT=mysalt
  #     - ENCRYPTION_KEY=b484dc3d77e194f02f3771e328ecd20d022c3c7a2699b1185b994a9513d1ebaa
  #     - AUTH_URL=http://localhost:3020
  #     - TELEMETRY_ENABLED=false
  #     - LANGFUSE_ENABLE_EXPERIMENTAL_FEATURES=true
  #     - LANGFUSE_INIT_ORG_ID=helperai
  #     - LANGFUSE_INIT_ORG_NAME=Helper.ai
  #     - LANGFUSE_INIT_PROJECT_ID=helperai
  #     - LANGFUSE_INIT_PROJECT_NAME=helper-ai-development
  #     - LANGFUSE_INIT_PROJECT_PUBLIC_KEY=pk-lf-c2d89bce-f43f-4587-8982-02e955b9b542
  #     - LANGFUSE_INIT_PROJECT_SECRET_KEY=sk-lf-7cf5475d-37f0-4734-9690-cd650c372934
  #     - LANGFUSE_INIT_USER_EMAIL=dev@helper.ai
  #     - LANGFUSE_INIT_USER_NAME=Helper.ai
  #     - LANGFUSE_INIT_USER_PASSWORD=password

volumes:
  helperai_pgdata:
